### ISSUE TITLE
Calculating addresses of call, jmp etc.

### ISSUE THREAD

**Issue by CallumCVM** [ZehMatt/zasm#13]
With zydis, you can call ZydisCalcAbsoluteAddressEx, but there is no way to retreive the relevant data to perform this from the `Decoder`.

Can you suggest any way to do this please?

**Comment by ZehMatt** [comment]
You actually don't need to, the resulting Instruction object has no relative immediates, you can just read the first operand and its value.
Something like this should work:
```cpp
if(auto* imm= instr.tryGetOperandAs<operands::Imm>(0); imm != nullptr)
{
   auto va = imm->value<uint64_t>();
}
```

**Comment by CallumCVM** [comment]
Great, thank you @ZehMatt, it works perfectly.
