### ISSUE TITLE
Calculating offset of memory operand type relative to instruction

### ISSUE THREAD

**Issue by CallumCVM** [ZehMatt/zasm#14]
![image](https://user-images.githubusercontent.com/15911764/147753323-6844479e-2e65-4346-a3e0-d08fa8897cd4.png)
 
In the above example I need to know the offset of the uint (highlighted in grey) for memory operands for the purposes of fixing up rva's in a mutation engine.

Please can you suggest a way to either extract the size of the mnemonic and I can work it out that way, or even better would be to know the offset of the bytes of the operand relative to the bytes of the full instruction.

Thanks :)

**Comment by ZehMatt** [comment]
I do have plans to add relocation support eventually as of now the Zydis encoder doesn't give us such information, your best bet is to decode the instruction with Zydis directly. You can use labels to get the instruction offset for the time being, I know its not the most optimal way.

**Comment by ZehMatt** [comment]
I've recently added support for relocating, you can read the relocation entries or tell zasm to relocate the code.
