### ISSUE TITLE
Performance problem.

### ISSUE THREAD

**Issue by Inori** [ZehMatt/zasm#17]
I'm currently writing a program which will reencode nearly every instruction of a big problem(a game).
So there will be millions of calls on reencode callback. (see [here](https://github.com/Inori/TinyDBR/blob/zasm/TinyDBR/arch/x86/x86_memory_controller.cpp#L42).)

The problem is that if I declare the `Program` and `Assembler` as local variables, then there will be millions of object/memory allocations and deallocations which will be a big impact on speed.

But if I declare them as global variables, I didn't see any clear methods so the generated code will be accumulated on every call.

Is there any solutions to this?

**Comment by ZehMatt** [comment]
You can destroy the nodes via ```program.destroy(node);```, clear would be the equivalent of traversing all nodes in the program and calling destroy. But having a clear method is definitely wanted.

**Comment by ZehMatt** [comment]
Also calling serialize multiple times will overwrite the previous generated code so you can re-use it as it is.

**Comment by ZehMatt** [comment]
I've added a clear method to Program in https://github.com/ZehMatt/zasm/commit/bfc3a16ac3d71ee6633beaeecdd7fd79fd37fbc1

If this is what you wanted feel free to close the issue.

**Comment by Inori** [comment]
> I've added a clear method to Program in [bfc3a16](https://github.com/ZehMatt/zasm/commit/bfc3a16ac3d71ee6633beaeecdd7fd79fd37fbc1)
> 
> If this is what you wanted feel free to close the issue.


Wow, thanks for you reply in such a short time.
The patch did what I want for sure. Thank you!

**Comment by Inori** [comment]
I'm sorry to reopen this.
After your fix, I still feels the program runs pretty slow, so I did some benchmark on popular asm jit encoders.
And I got the following result:

```
Average output for test several times:

Debug Build:
Asmjit 79.5586 ms
Xbyak 268.761 ms
Zasm 34107.5 ms

Release Build:
Asmjit 7.0578 ms
Xbyak 13.9802 ms
Zasm 6339.41 ms
```
zasm get unexpected performance compared to the other two engine.

I'm not 100% sure I use there library correctly, but all I want is to get new generated code buffer on each loop.
Can you give me some advice?

The test code can be found [here](https://github.com/Inori/X86AsmEncoderBenchmark/blob/master/X86AsmEncoderBenchmark/main.cpp).
I upload the benchmark project for anyone who wanna a try.

**Comment by Inori** [comment]
I add Zydis encoder test.
Seems Zydis encoder itself is acceptable.

```
CPU: Intel i7-8700
Average output for test several times:

Debug Build:

Asmjit 77.5361 ms
Xbyak 206.549 ms
Zydis 88.2653 ms
Zasm 31610.4 ms


Release Build:

Asmjit 6.3319 ms
Xbyak 11.3565 ms
Zydis 25.2644 ms
Zasm 6156.57 ms
```

**Comment by ZehMatt** [comment]
> 

I've tried to reproduce the issue where getCode() and adapted a test for this. Unfortunately I can't reproduce the issue, the test looks like following: https://gist.github.com/ZehMatt/1b45af7ac60b076ff97eccb82acd017f

Regarding performance, I didn't get to optimize anything just yet, keep in mind that zasm is a general purpose assembler while zydis encoder is just purely an encoder, zasm implements labels and sections and also stores instruction as nodes to allow re-ordering so there is an added cost. I want to look into optimizing it a bit at some point but right now I'm still more focused on adding essential features and having the general API as user friendly as possible.

**Comment by ZehMatt** [comment]
I also just realized you are testing the Assembler in asmjit, to have a fair comparison you would need to compare asmjits Builder.

**Comment by ZehMatt** [comment]
I just merged a PR where I did some smaller performance improvements. To keep in mind I'm not trying to compete with asmjit, this is more focused towards tooling where performance is not as super important.

**Comment by Inori** [comment]
OK, I see.
zasm is designed as a full featured assembler, not a jit asm compiler, which is what I need.
